"""report_utils.py - builds the one-page PDF design report (fpdf2, no heavy deps).

The Pareto chart is drawn with PDF vector primitives (axes, gridlines, polyline,
marker) instead of rasterising a plotly/matplotlib figure, so the report needs
no kaleido/matplotlib and stays trivially light for Streamlit Community Cloud.
PDF core fonts are latin-1, so variable names use ASCII forms (R_th, dP_tot).
"""
import datetime

import numpy as np
from fpdf import FPDF

import core

INK = (26, 34, 48)
BLUE = (31, 95, 176)
RED = (192, 57, 43)
MUT = (90, 102, 117)
GRID = (225, 230, 238)


class _Report(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 15)
        self.set_text_color(*BLUE)
        self.cell(0, 8, "Heat-Pipe Surrogate - Design Report", align="C",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*MUT)
        self.cell(0, 5, datetime.date.today().isoformat() +
                  "  |  generated by the Heat-Pipe Surrogate & Design Optimiser web app",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*MUT)
        self.cell(0, 5, "Shubhamshree Avishek, Dr. Koushik Das - Department of Mechanical "
                        "Engineering, NIT Meghalaya, India", align="C")

    # ---- small helpers ----------------------------------------------------- #
    def h2(self, txt):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*INK)
        self.cell(0, 7, txt, new_x="LMARGIN", new_y="NEXT")

    def kv(self, key, val, key_w=62):
        self.set_font("Helvetica", "", 9.5)
        self.set_text_color(*MUT)
        self.cell(key_w, 5.4, key)
        self.set_text_color(*INK)
        self.set_font("Helvetica", "B", 9.5)
        self.multi_cell(0, 5.4, str(val), new_x="LMARGIN", new_y="NEXT")


def _pareto_chart(pdf, caps, R, sol, ptot_max, x0, y0, w, h):
    """Hand-drawn vector line chart: R_th* vs pressure-drop cap."""
    ok = ~np.isnan(R)
    xs, ys = np.asarray(caps)[ok], np.asarray(R)[ok]
    if xs.size < 2:
        return
    x_lo, x_hi = float(xs.min()), float(xs.max())
    y_lo, y_hi = float(ys.min()), float(ys.max())
    y_pad = 0.08 * (y_hi - y_lo if y_hi > y_lo else 1.0)
    y_lo, y_hi = y_lo - y_pad, y_hi + y_pad

    def X(v): return x0 + (v - x_lo) / (x_hi - x_lo) * w
    def Y(v): return y0 + h - (v - y_lo) / (y_hi - y_lo) * h

    # frame + gridlines + tick labels
    pdf.set_draw_color(*GRID)
    pdf.set_line_width(0.2)
    pdf.set_font("Helvetica", "", 7)
    pdf.set_text_color(*MUT)
    for i in range(5):
        gx = x_lo + i * (x_hi - x_lo) / 4
        gy = y_lo + i * (y_hi - y_lo) / 4
        pdf.line(X(gx), y0, X(gx), y0 + h)
        pdf.line(x0, Y(gy), x0 + w, Y(gy))
        pdf.text(X(gx) - 4, y0 + h + 4, f"{gx:,.0f}")
        pdf.text(x0 - 13, Y(gy) + 1, f"{gy:.3f}")
    pdf.set_draw_color(60, 70, 86)
    pdf.set_line_width(0.4)
    pdf.rect(x0, y0, w, h)

    # constraint line (dashed)
    if x_lo <= ptot_max <= x_hi:
        pdf.set_draw_color(*RED)
        pdf.set_line_width(0.35)
        yy = y0
        while yy < y0 + h:
            pdf.line(X(ptot_max), yy, X(ptot_max), min(yy + 2.2, y0 + h))
            yy += 4.4

    # Pareto polyline + points
    pdf.set_draw_color(*BLUE)
    pdf.set_line_width(0.5)
    for i in range(len(xs) - 1):
        pdf.line(X(xs[i]), Y(ys[i]), X(xs[i + 1]), Y(ys[i + 1]))
    pdf.set_fill_color(*BLUE)
    for xi, yi in zip(xs, ys):
        pdf.circle(X(xi) - 0.8, Y(yi) - 0.8, 1.6, style="F")

    # optimum marker
    if sol is not None:
        pdf.set_fill_color(*RED)
        pdf.circle(X(sol["p_tot"]) - 1.4, Y(sol["r_th"]) - 1.4, 2.8, style="F")

    # axis titles
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*INK)
    pdf.text(x0 + w / 2 - 14, y0 + h + 9, "dP_tot cap (Pa)")
    with pdf.rotation(90, x0 - 16, y0 + h / 2 + 10):
        pdf.text(x0 - 16, y0 + h / 2 + 10, "min R_th (K/W)")


def build_report_pdf(assets, ptot_max, sol, other, caps, Rfront, sens, status) -> bytes:
    pdf = _Report(format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()

    # ---- provenance -------------------------------------------------------- #
    pdf.h2("1. Surrogate provenance")
    m = assets.manifest
    pdf.kv("Best model (LOOCV-selected)", assets.model_name)
    if m.get("loocv_overall_r2") is not None:
        pdf.kv("LOOCV overall R2", f"{m['loocv_overall_r2']:.4f}")
    if m.get("loocv_overall_mae") is not None and m.get("loocv_overall_mse") is not None:
        pdf.kv("LOOCV MAE / RMSE", f"{m['loocv_overall_mae']:.4g} / {m['loocv_overall_mse']**0.5:.4g}")
    pdf.kv("Training samples (n)", assets.n if assets.n else "unknown")
    pdf.kv("Design space", f"Vp:Vs in [{assets.LB[0]:.3f}, {assets.UB[0]:.3f}],  "
                           f"porosity in [{assets.LB[1]:.3f}, {assets.UB[1]:.3f}]")
    pdf.kv("Fixed parameters", f"Q = {core.Q_WATT:.0f} W,  A_c = {core.A_CROSS:.3g} m2,  "
                               f"L_eff = {core.L_EFF:.2f} m")
    pdf.ln(1.5)

    # ---- optimum ------------------------------------------------------------ #
    pdf.h2(f"2. Constrained optimum  (dP_tot <= {ptot_max:,.0f} Pa)")
    if sol is None:
        pdf.kv("Result", "No feasible design at this limit.")
    else:
        keq = core.k_eq_from_rth(sol["r_th"])
        pdf.kv("Optimal design", f"Vp:Vs = {sol['vp_vs']:.4f},  porosity = {sol['po']:.4f}")
        pdf.kv("R_th* (min. resistance)", f"{sol['r_th']:.4f} K/W")
        pdf.kv("dP_tot* / slack", f"{sol['p_tot']:.1f} Pa  /  {sol['slack']:.1f} Pa")
        pdf.kv("k_eq* (equivalent conductivity)", f"{keq:,.0f} W/m/K")
        pdf.kv("Solver", "SLSQP (multi-start), gradient-based, native inequality constraint")
        if other is not None:
            pdf.kv("Grid-search cross-check", f"R_th diff {abs(other['r_th']-sol['r_th']):.2e} K/W "
                                              f"(steps 0.05 / 0.01)")
        if status is not None:
            pct = status.get("pct", float("nan"))
            pct_txt = f", GPR sigma percentile {pct:.0f}" if pct == pct else ""
            pdf.kv("Domain trust at optimum",
                   f"{status['level']} ({'inside' if status['in_hull'] else 'outside'} "
                   f"convex hull{pct_txt})")
    pdf.ln(1.5)

    # ---- sensitivities ------------------------------------------------------ #
    if sens:
        pdf.h2("3. Local sensitivities at the optimum (central differences)")
        pdf.kv("dR_th/d(Vp:Vs)", f"{sens['dr_dvp']:+.4f} K/W per unit ratio")
        pdf.kv("dR_th/d(porosity)", f"{sens['dr_dpo']:+.4f} K/W per unit porosity")
        pdf.kv("d(dP_tot)/d(Vp:Vs)", f"{sens['dp_dvp']:+,.0f} Pa per unit ratio")
        pdf.kv("d(dP_tot)/d(porosity)", f"{sens['dp_dpo']:+,.0f} Pa per unit porosity")
        pdf.ln(1.5)

    # ---- Pareto chart -------------------------------------------------------- #
    pdf.h2("4. Resistance / pressure-drop trade-off (Pareto front)")
    y_chart = pdf.get_y() + 2
    _pareto_chart(pdf, caps, Rfront, sol, ptot_max, x0=38, y0=y_chart, w=130, h=52)
    pdf.set_y(y_chart + 52 + 12)
    pdf.set_font("Helvetica", "", 8.5)
    pdf.set_text_color(*MUT)
    pdf.multi_cell(0, 4.4,
                   "Each point is the minimum achievable thermal resistance at a given "
                   "pressure-drop cap; the dashed line marks the active limit and the red "
                   "marker the reported optimum. The local slope is the constraint shadow "
                   "price - resistance bought per extra Pa of allowable pressure drop.")

    out = pdf.output()
    return bytes(out)
