"""report_utils.py - builds the one-page PDF design report (fpdf2).

Typography: the report embeds Liberation Serif (shipped in fonts/), a
metrically Times-compatible serif with full Greek coverage, so the whole
document renders in a Times New Roman style with true italics, real
subscripts (R_th as italic R + subscript th) and proper Delta/epsilon glyphs.
Falls back to core Times + ASCII names only if the font files are missing.

The Pareto chart is drawn with vector primitives: nice 1-2-5 tick spacing,
major AND minor gridlines, the x-range cropped to the informative part of the
front (around the constraint), the limit dashed, and the optimum starred.
"""
import os
import datetime

import numpy as np
from fpdf import FPDF

import core

INK = (26, 34, 48)
BLUE = (31, 95, 176)
RED = (192, 57, 43)
MUT = (90, 102, 117)
GRID_MAJ = (200, 208, 220)
GRID_MIN = (233, 237, 243)

_FONT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fonts")


def _nice_ticks(lo, hi, target=5):
    """1-2-5 major tick positions covering [lo, hi], plus the minor step."""
    span = hi - lo
    raw = span / max(target, 1)
    mag = 10 ** np.floor(np.log10(raw))
    for mult in (1, 2, 5, 10):
        if raw <= mult * mag:
            step = mult * mag
            break
    minor = step / (4 if mult in (2, 10) else 5)
    t0 = np.ceil(lo / step) * step
    majors = np.arange(t0, hi + 1e-9, step)
    m0 = np.ceil(lo / minor) * minor
    minors = np.arange(m0, hi + 1e-9, minor)
    return majors, minors, step


class _Report(FPDF):
    def __init__(self, *a, **k):
        super().__init__(*a, **k)
        self.serif = "Times"
        self.uni = False
        try:
            self.add_font("Lib", "", os.path.join(_FONT_DIR, "LiberationSerif-Regular.ttf"))
            self.add_font("Lib", "B", os.path.join(_FONT_DIR, "LiberationSerif-Bold.ttf"))
            self.add_font("Lib", "I", os.path.join(_FONT_DIR, "LiberationSerif-Italic.ttf"))
            self.add_font("Lib", "BI", os.path.join(_FONT_DIR, "LiberationSerif-BoldItalic.ttf"))
            self.serif, self.uni = "Lib", True
        except Exception:
            pass

    # ---- rich text: list of (text, style, vpos) runs ----------------------- #
    def rich(self, runs, size=9.5):
        for text, style, vpos in runs:
            self.set_font(self.serif, style, size)
            self.char_vpos = vpos or "LINE"
            self.write(5.4, text)
        self.char_vpos = "LINE"

    def sym_rth(self):
        return [("R", "I", None), ("th", "", "SUB")]

    def sym_ptot(self):
        d = "\u0394" if self.uni else "d"
        return [(d, "", None), ("P", "I", None), ("tot", "", "SUB")]

    def sym_keq(self):
        return [("k", "I", None), ("eq", "", "SUB")]

    def header(self):
        self.set_font(self.serif, "B", 15)
        self.set_text_color(*BLUE)
        self.cell(0, 8, "Hybrid Surrogate Model - Design Report", align="C",
                  new_x="LMARGIN", new_y="NEXT")
        self.set_font(self.serif, "", 9)
        self.set_text_color(*MUT)
        self.cell(0, 5, datetime.date.today().isoformat() +
                  "  |  generated by the Hybrid Surrogate Model web application",
                  align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self):
        self.set_y(-12)
        self.set_font(self.serif, "I", 8)
        self.set_text_color(*MUT)
        self.cell(0, 5, "Shubhamshree Avishek, Dr. Koushik Das - Department of Mechanical Engineering, "
                        "NIT Meghalaya, Sohra, Meghalaya, India - 793108", align="C")

    def h2(self, txt):
        self.set_font(self.serif, "B", 11)
        self.set_text_color(*INK)
        self.cell(0, 7, txt, new_x="LMARGIN", new_y="NEXT")

    def kv(self, key_runs, val, key_w=64):
        """key_runs: plain string OR list of rich runs."""
        x0 = self.get_x()
        self.set_text_color(*MUT)
        if isinstance(key_runs, str):
            self.set_font(self.serif, "", 9.5)
            self.cell(key_w, 5.4, key_runs)
        else:
            self.rich(key_runs, size=9.5)
            self.set_x(x0 + key_w)
        self.set_text_color(*INK)
        self.set_font(self.serif, "B", 9.5)
        self.multi_cell(0, 5.4, str(val), new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(*INK)


def _pareto_chart(pdf, caps, R, sol, ptot_max, x0, y0, w, h):
    ok = ~np.isnan(np.asarray(R, float))
    xs, ys = np.asarray(caps, float)[ok], np.asarray(R, float)[ok]
    if xs.size < 2:
        return
    # crop to the informative range around the constraint (flat tail adds nothing)
    x_hi_crop = min(float(xs.max()), max(2.2 * ptot_max, float(xs.min()) * 1.5))
    keep = xs <= x_hi_crop + 1e-9
    xs, ys = xs[keep], ys[keep]
    x_lo, x_hi = float(xs.min()), float(xs.max())
    y_lo, y_hi = float(ys.min()), float(ys.max())
    y_pad = 0.10 * (y_hi - y_lo if y_hi > y_lo else 1.0)
    y_lo, y_hi = y_lo - y_pad, y_hi + y_pad

    def X(v): return x0 + (v - x_lo) / (x_hi - x_lo) * w
    def Y(v): return y0 + h - (v - y_lo) / (y_hi - y_lo) * h

    xa_maj, xa_min, _ = _nice_ticks(x_lo, x_hi, 5)
    ya_maj, ya_min, _ = _nice_ticks(y_lo, y_hi, 4)

    # minor grid
    pdf.set_draw_color(*GRID_MIN); pdf.set_line_width(0.14)
    for gx in xa_min: pdf.line(X(gx), y0, X(gx), y0 + h)
    for gy in ya_min: pdf.line(x0, Y(gy), x0 + w, Y(gy))
    # major grid + tick labels
    pdf.set_draw_color(*GRID_MAJ); pdf.set_line_width(0.24)
    pdf.set_font(pdf.serif, "", 7.5); pdf.set_text_color(*MUT)
    for gx in xa_maj:
        pdf.line(X(gx), y0, X(gx), y0 + h)
        lbl = f"{gx:,.0f}"
        pdf.text(X(gx) - pdf.get_string_width(lbl) / 2, y0 + h + 4, lbl)
    for gy in ya_maj:
        pdf.line(x0, Y(gy), x0 + w, Y(gy))
        lbl = f"{gy:.2f}"
        pdf.text(x0 - pdf.get_string_width(lbl) - 2, Y(gy) + 1.1, lbl)
    # frame
    pdf.set_draw_color(60, 70, 86); pdf.set_line_width(0.45)
    pdf.rect(x0, y0, w, h)

    # constraint (dashed red vertical)
    if x_lo <= ptot_max <= x_hi:
        pdf.set_draw_color(*RED); pdf.set_line_width(0.4)
        yy = y0
        while yy < y0 + h:
            pdf.line(X(ptot_max), yy, X(ptot_max), min(yy + 2.0, y0 + h))
            yy += 4.0

    # Pareto polyline + points
    pdf.set_draw_color(*BLUE); pdf.set_line_width(0.55)
    for i in range(len(xs) - 1):
        pdf.line(X(xs[i]), Y(ys[i]), X(xs[i + 1]), Y(ys[i + 1]))
    pdf.set_fill_color(*BLUE)
    for xi, yi in zip(xs, ys):
        pdf.circle(X(xi) - 0.75, Y(yi) - 0.75, 1.5, style="F")
    # optimum
    if sol is not None and x_lo <= sol["p_tot"] <= x_hi:
        pdf.set_fill_color(*RED)
        pdf.circle(X(sol["p_tot"]) - 1.5, Y(sol["r_th"]) - 1.5, 3.0, style="F")

    # axis titles with true italics/subscripts
    pdf.set_text_color(*INK)
    pdf.set_xy(x0 + w / 2 - 12, y0 + h + 6.5)
    pdf.rich(pdf.sym_ptot() + [(" cap (Pa)", "", None)], size=9)
    with pdf.rotation(90, x0 - 15, y0 + h / 2 + 12):
        pdf.set_xy(x0 - 15, y0 + h / 2 + 12)
        pdf.rich([("min ", "", None)] + pdf.sym_rth() + [(" (K/W)", "", None)], size=9)

    # legend line under the chart
    pdf.set_xy(x0, y0 + h + 11)
    pdf.set_font(pdf.serif, "", 8); pdf.set_text_color(*MUT)
    pdf.write(4.4, "blue = Pareto front;  dashed red = active limit;  red marker = reported optimum")


def yield_analysis(assets, sol, ptot_max, tol_vp, tol_po, n_mc=20000, seed=42):
    """Monte-Carlo manufacturing yield around the optimum (Normal, tol = 3-sigma)."""
    rng = np.random.default_rng(seed)
    vp = rng.normal(sol["vp_vs"], tol_vp / 3.0, n_mc)
    po = rng.normal(sol["po"], tol_po / 3.0, n_mc)
    vp = np.clip(vp, *core.BOUNDS["vp_vs"]); po = np.clip(po, *core.BOUNDS["po"])
    y = core.predict(assets, np.column_stack([vp, po]))
    r, p = y[:, 0], y[:, 1]
    return {"yield_pct": float(np.mean(p <= ptot_max) * 100.0),
            "r_mean": float(r.mean()), "r_std": float(r.std()),
            "r_p95": float(np.quantile(r, 0.95)),
            "p_mean": float(p.mean()), "p_std": float(p.std()),
            "n_mc": int(n_mc), "tol_vp": float(tol_vp), "tol_po": float(tol_po)}


def build_report_pdf(assets, ptot_max, sol, other, caps, Rfront, status,
                     yld=None, metrics=None) -> bytes:
    pdf = _Report(format="A4")
    pdf.set_auto_page_break(auto=True, margin=16)
    pdf.add_page()
    eps = "\u03b5" if pdf.uni else "eps"

    # ---- 1. provenance ------------------------------------------------------ #
    pdf.h2("1. Surrogate provenance")
    pdf.kv("Best model (LOOCV-selected)", assets.model_name)
    pdf.kv("Training samples (n)", assets.n if assets.n else "unknown")
    pdf.kv("Design space", f"Vp:Vs in [{assets.LB[0]:.3f}, {assets.UB[0]:.3f}],  "
                           f"{eps} in [{assets.LB[1]:.3f}, {assets.UB[1]:.3f}]")
    pdf.kv("Fixed parameters", f"Q = {core.Q_WATT:.0f} W,  A_c = {core.A_CROSS:.3g} m2,  "
                               f"L_eff = {core.L_EFF:.2f} m")
    pdf.ln(1.5)

    # ---- 2. model provenance & performance metrics --------------------------- #
    pdf.h2(f"2. Model provenance & performance ({assets.model_name}, leave-one-out CV)")
    mt = metrics or {}
    if mt.get("kernel"):
        pdf.kv("Kernel", mt["kernel"])
    if mt.get("r2") is not None:
        pdf.kv("Overall R2", f"{mt['r2']:.3f}")
    if mt.get("mae") is not None:
        pdf.kv("Overall MAE", f"{mt['mae']:.4g}")
    if mt.get("mse") is not None:
        pdf.kv("Overall MSE", f"{mt['mse']:.4g}")
    if mt.get("rmse") is not None:
        pdf.kv("Overall RMSE", f"{mt['rmse']:.4g}")
    if not any(mt.get(k) is not None for k in ("r2", "mae", "mse", "rmse")):
        pdf.kv("Metrics", "not found in the manifests shipped with the artifacts")
    if mt.get("basis"):
        pdf.kv("Selection basis", mt["basis"])
    if mt.get("sklearn_version"):
        pdf.kv("scikit-learn (pickled with)", mt["sklearn_version"])
    pdf.kv("Output transform", "dP_tot modelled in log1p space; predictions back-transformed")
    pdf.ln(1.5)

    # ---- 3. constrained optimum --------------------------------------------- #
    pdf.h2(f"3. Constrained optimum  (limit {ptot_max:,.2f} Pa)")
    if sol is None:
        pdf.kv("Result", "No feasible design at this limit.")
    else:
        keq = core.k_eq_from_rth(sol["r_th"])
        pdf.kv("Optimal design", f"Vp:Vs = {sol['vp_vs']:.4f},  {eps} = {sol['po']:.4f}")
        pdf.kv("Min. thermal resistance", f"{sol['r_th']:.3f} K/W")
        pdf.kv("Pressure drop / slack", f"{sol['p_tot']:.2f} Pa  /  {sol['slack']:.2f} Pa")
        pdf.kv("Equivalent conductivity", f"{keq:,.0f} W/m/K")
        pdf.kv("Solver", "SLSQP (multi-start), native inequality constraint")
        if other is not None:
            pdf.kv("Grid-search cross-check",
                   f"R_th difference {abs(other['r_th']-sol['r_th']):.2e} K/W (steps 0.05 / 0.01)")
        if status is not None:
            pct = status.get("pct", float("nan"))
            pct_txt = f", sigma percentile {pct:.0f}" if pct == pct else ""
            pdf.kv("Domain trust at optimum",
                   f"{status['level']} ({'inside' if status['in_hull'] else 'outside'} "
                   f"convex hull{pct_txt})")
    pdf.ln(1.5)

    # ---- 4. manufacturing yield --------------------------------------------- #
    if yld is not None and sol is not None:
        pdf.h2("4. Manufacturing yield at the optimum (Monte-Carlo)")
        pdf.kv("Tolerances (+/-, 3-sigma Normal)",
               f"Vp:Vs {yld['tol_vp']:.3f},  {eps} {yld['tol_po']:.3f}   "
               f"({yld['n_mc']:,} samples)")
        pdf.kv("Yield P(dP_tot <= limit)", f"{yld['yield_pct']:.1f} %")
        pdf.kv("R_th under scatter", f"mean {yld['r_mean']:.3f} K/W,  "
                                     f"std {yld['r_std']:.3f},  95th pct {yld['r_p95']:.3f}")
        pdf.kv("dP_tot under scatter", f"mean {yld['p_mean']:.2f} Pa,  std {yld['p_std']:.2f}")
        pdf.ln(1.5)

    # ---- 5. Pareto front ------------------------------------------------------ #
    pdf.h2("5. Resistance / pressure-drop trade-off (Pareto front)")
    y_chart = pdf.get_y() + 3
    _pareto_chart(pdf, caps, Rfront, sol, ptot_max, x0=40, y0=y_chart, w=125, h=48)
    pdf.set_y(y_chart + 48 + 16)
    pdf.set_font(pdf.serif, "", 8.5)
    pdf.set_text_color(*MUT)
    pdf.multi_cell(0, 4.4,
                   "Each point is the minimum achievable thermal resistance at a given "
                   "pressure-drop cap (x-axis cropped to the informative region around the "
                   "limit). The local slope is the constraint shadow price - resistance "
                   "bought per extra Pa of allowable pressure drop.")
    return bytes(pdf.output())
